language: python

sudo: required

services:
  - docker

before_install:
  - docker build -t alekcoraglez/flask-app-docker-test ./flask-app-blueprint

script:
  - docker run alekcoraglez/flask-app-docker-test python manage.py test

after_success:
  - docker build -t alekcoraglez/flask-app-docker ./flask-app-blueprint

  # Login into Docker CLI...
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images
  - docker push alekcoraglez/flask-app-docker

deploy:
  app: flask-app
  env: FlaskApp-env
  provider: elasticbeanstalk
  region: us-east-1
  edge: true

  bucket: elasticbeanstalk-us-east-1-241862480583

  on:
    branch: develop

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
