apiVersion: v1
kind: Pod

metadata:
  name: flask-app-pod
  labels:
    component: flask-app

spec:
  containers:
    - name: flask-app
      image: alekcoraglez/flask-app-docker
      ports:
        - containerPort: 5000
